### ISSUE TITLE
add images to gist markdowns

### ISSUE THREAD

**Issue by ThuyNT13** [LearnTeachCode/algorithms-group#1]
@LearningNerd, if you have the time could you get images from the Google Doc and upload them to the appropriate gists? Most of the contents are up but I haven't had time to include images. I've split the google doc up into 2 separate gists: 
  - [LinkedList gist](https://gist.github.com/ThuyNT13/85815881d64061ef3e21671a233f8e43)
  - [Big O Notation gist](https://gist.github.com/ThuyNT13/16bc1cf4242e5e2ba84d20c47be793b0)

[Big O Notation and Linked Lists google doc](https://docs.google.com/document/d/1qKmqU6BfsG_HjirYaHY2VCnXGpGCOZlpasUG4wLpk7k)

**Comment by LearningNerd** [comment]
Hi @ThuyNT13 this looks awesome! :) Hmm, doesn't seem like I can upload photos to use within a Gist. (I tried forking the Gist and editing but no luck with adding an image.)

I think this would be easier inside a dedicated repo instead of using Gists. We could post the Markdown files and upload images directly into this repo right here, and maybe just link to the files in the README as a little table of contents?

Inserting images straight into this issue for now. You should be able to copy-paste the image link from this issue into the notes:
![big-o-complexity](https://user-images.githubusercontent.com/1555022/34961451-04812f50-f9f4-11e7-92a5-350689f3fb55.png)

![dsa_linkedlist](https://user-images.githubusercontent.com/1555022/34961473-1c9daf82-f9f4-11e7-90f2-45715b015edf.jpg)

**Comment by ThuyNT13** [comment]
@LearningNerd ok figured out how to do it. I embedded the images above using the `![title](link)` syntax with the caveat being that it had to be stored as a `githubusercontent` file or some other sort of permanent image file location. I tried to add it as a file inside the gist itself and use the link to the image but that didn't work so ¯\_(ツ)_/¯

**Comment by ThuyNT13** [comment]
thank you!
